spring:
  application:
    name: RogueMice
  datasource:
    url: jdbc:mysql://localhost:3306/manageStudent
    username: root
    password: Roguemice2002@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true